#!/usr/bin/env ruby

task :test_ios => [] do
    systems = ['7.1', '8.1']
    sdks = ['iphonesimulator']

    sdks.each do |sdk|
        systems.each do |sys|
            fail unless system("xcodebuild", "-workspace", "Slash.xcworkspace", '-scheme', 'Slash-iOS', '-sdk', sdk, '-configuration', 'Release', 'test', '-destination', "platform=iOS Simulator,OS=#{sys},name=iPhone 5")
        end
    end
end

task :test_mac => [] do
    sdks = ['macosx']

    sdks.each do |sdk|
        fail unless system("xcodebuild", "-workspace", "Slash.xcworkspace", '-scheme', 'Slash-OSX', '-sdk', sdk, '-configuration', 'Release', 'test', '-destination', "platform=OS X")
    end
end

task :default => [:test_mac, :test_ios]
